[env:esp32dev]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
monitor_speed = 115200
upload_port = /dev/ttyUSB0 # This command lists all devices in /dev/ttyUSB* and sets the first one as the upload port. It's used to automatically select the correct USB port for uploading the firmware.
# Steps to ensure WSL can read ESP32:
# (1) In cmd(admin) enter: usbipd list
# (2) In cmd(admin) enter: usbipd attach --wsl --busid=<BUSID>
# (3) In cmd(admin) enter the following to find BUSID: usbipd list 
monitor_filters = esp32_exception_decoder # this filter will decode exceptions and print the stack trace in a human-readable format, which is very helpful for debugging crashes and exceptions on the ESP32.

lib_deps =
    MFRC522
    adafruit/Adafruit SSD1306 @ ^2.5.16
